language: node_js
sudo: false

node_js:
  - '5.6.0'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

install:
  - npm install
  - npm run typings

script:
- npm run test
