language: node_js
sudo: false

node_js:
  - '7'

cache:
  yarn: true
  directories:
    - node_modules

script:
- yarn run travis

after_success:
-  cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
