language: node_js
sudo: false

node_js:
  - '5.6.0'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

install:
  - npm install

script:
- npm run test

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
